### ISSUE TITLE
你好，这个项目没有上传页面文件吗

### ISSUE THREAD

**Issue by yangliu0404** [serfend/Project.Web.SfMVC.TrainSchdule.1903#1]
你好，这个项目没有上传页面文件吗？能否正常运行。只是学习看一下，并非商用。

**Comment by serfend** [comment]
感谢你的关注，可参见[前端项目](https://github.com/serfend/Project.Web.Front.Vue.TrainSchdule.1911)

**Comment by yangliu0404** [comment]
> 感谢你的关注，可参见[前端项目](https://github.com/serfend/Project.Web.Front.Vue.TrainSchdule.1911)

看到了，谢谢。
